ALTER TABLE medi001.doctores 
ADD COLUMN IF NOT EXISTS es_medico BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS titulo TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS titulo_academico TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS num_mpps TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS num_cm TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS rif TEXT DEFAULT '';
